### ISSUE TITLE
Equip on Field Terminal Critical bug

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#23]
This will be addressed with preliminary task of hiding to remove from game client.
Then later tackled and reintroduced when resolved.

**Comment by LoyalServant** [comment]
[15:17:23] ERR
Exception Found:
Type: System.InvalidOperationException
Message: The current TransactionScope is already complete.
Source: System.Transactions
Stacktrace:    at System.Transactions.Transaction.get_Current()
   at Perpetuum.RequestHandlers.FittingPreset.FittingPresetRequestHandler.SendAllPresetsToCharacter(IRequest request, IFittingPresetRepository repo)
   at Perpetuum.RequestHandlers.FittingPreset.FittingPresetList.HandleRequest(IRequest request)
   at Perpetuum.Host.Requests.RequestHandlerProfiler1.<>c__DisplayClass2_0.<HandleRequest>b__0()
   at Perpetuum.Profiler.ExecutionTimeOf(Action action)
   at Perpetuum.Host.Requests.RequestHandlerProfiler1.HandleRequest(T request)
   at Perpetuum.Services.Sessions.Session.HandleRequest(IRequest request)
   at Perpetuum.Services.Sessions.Session.OnDataReceived(ITcpConnection connection, Byte[] receivedData)

**Comment by MikeJeffers** [comment]
closed by OpenPerpetuum/PerpetuumServer@ce1cce08fc1bd86b3e99b62ea0f6
