### ISSUE TITLE
Syntax error!?

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/OP-Project#64]
```
[21:30:03] INF [PROFILE] marketGetAveragePrices time:11.40ms
[21:30:05] ERR 
Exception Found:
Type: System.Data.SqlClient.SqlException
Message: Incorrect syntax near ')'.
Source: .Net SqlClient Data Provider
Stacktrace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Perpetuum.Data.DbQuery.<>c.<Execute>b__8_0(IDbCommand cmd)
   at Perpetuum.Data.DbQuery.ExecuteHelper[T](Func`2 execute)
   at Perpetuum.Data.DbQuery.Execute()
   at Perpetuum.Services.MarketEngine.MarketHandler.GetGlobalAverageHistory(Int32 day, Int32 itemDefinition)
   at Perpetuum.RequestHandlers.Markets.MarketGlobalAveragePrices.HandleRequest(IRequest request)
   at Perpetuum.Host.Requests.RequestHandlerProfiler`1.<>c__DisplayClass2_0.<HandleRequest>b__0()
   at Perpetuum.Profiler.ExecutionTimeOf(Action action)
   at Perpetuum.Host.Requests.RequestHandlerProfiler`1.HandleRequest(T request)
   at Perpetuum.Services.Sessions.Session.HandleRequest(IRequest request)
   at Perpetuum.Services.Sessions.Session.OnDataReceived(ITcpConnection connection, Byte[] receivedData)
```

**Comment by MikeJeffers** [comment]
Nevermind this was a DB issue; resolved
