### ISSUE TITLE
Server error when creating player corporation

### ISSUE THREAD

**Issue by LoyalServant** [OpenPerpetuum/OP-Project#8]
Client returns "server error"

**Comment by LoyalServant** [comment]
Log information:
`[14:18:47] ERR 
Exception Found:
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Perpetuum
Stacktrace:    at Perpetuum.Groups.Corporations.CorporationManager.InformCorporationMemberTransferred(Corporation oldCorporation, Corporation newCorporation, Character member, Character kicker)
   at Perpetuum.Groups.Corporations.CorporationManager.InformCorporationMemberTransferred(Corporation oldCorporation, Corporation newCorporation, Character member)
   at Perpetuum.RequestHandlers.Corporations.CorporationCreate.HandleRequest(IRequest request)
   at Perpetuum.Profiler.ExecutionTimeOf(Action action)
   at Perpetuum.Host.Requests.RequestHandlerProfiler`1.HandleRequest(T request)
   at Perpetuum.Services.Sessions.Session.OnDataReceived(ITcpConnection connection, Byte[] receivedData)
[14:18:47] INF [PROFILE] corporationGetMyInfo time:2.13ms`

**Comment by MikeJeffers** [comment]
Reported as working @12/28/2017
